# Generated by Django 4.0.4 on 2022-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='fullname', max_length=200),
        ),
    ]
