# Generated by Django 4.0.4 on 2022-05-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_user_isproducer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('publish_date', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('lastUpdated', models.DateTimeField()),
                ('isPublic', models.BooleanField()),
                ('isPrivate', models.BooleanField()),
                ('isUnlisted', models.BooleanField()),
                ('quality', models.CharField(default='1920x1080', max_length=200)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
