# Generated by Django 4.0.4 on 2022-05-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isProducer',
        ),
    ]
