# Generated by Django 4.0.4 on 2022-05-22 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_rename_movie_video_view_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 12, 0, 17, 62058)),
        ),
    ]
