# Generated by Django 4.0.4 on 2022-05-22 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_alter_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storyboard',
            name='video',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videobanner',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/default.png', upload_to='uploads/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/user_banners/default.png', upload_to='uploads/user_banners/'),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/video_banners/default.png', upload_to='uploads/video_banners/'),
        ),
        migrations.AddField(
            model_name='video',
            name='banner_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='storyboard',
            field=models.ImageField(blank=True, default='uploads/video_storyboards/default.png', upload_to='uploads/video_storyboards/'),
        ),
        migrations.AddField(
            model_name='video',
            name='storyboard_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='uploads/video_thumbnails/default.png', upload_to='uploads/video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Storyboard',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
        migrations.DeleteModel(
            name='VideoBanner',
        ),
    ]
