# Generated by Django 4.0.4 on 2022-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_remove_banner_user_remove_storyboard_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
